name: weather_app
description: A simple weather app using Dio for networking.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  geolocator: ^13.0.1
  shared_preferences: ^2.3.2
<<<<<<< HEAD
  flutter_svg: ^2.0.10
=======
  geocoding: ^4.0.0
>>>>>>> 40f5d9d (Version 3)

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/weather/